sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.0"
  - "stable"
env:
  global:
    - secure: "w+MP7I2qqrMa7hrfvJ/UEaUN1X2laibd3saGirqMlBDIeD2EiCSNWMPF+dOPKKIH6D63FaQmpI38i6vrP+187LL0b46QcRkE7fPzq0CQuDyWXvkTIpLunrRdiog4GjbJ3BGFUewMwV/mx7MiKIkRxvCyK9xW3zdOicE/Yz/GdXSk3OOd5W/8OyRNlJrjU5zyVtcb9wSEbP/2HHaVp/daXqWrp68SQqZNlJcb5yM7C9gP9JZNN3GX/4gbpFwxdtYy5657v9Kx9WLyQe87S8CZleilXFfrV3s3YIeJnJVLku2OznHune8l4k+MaoCav7x0pHFh70pdOlkYdAJFCY1IDrHtvLIeEGmjrJVbycFvcCu2V5O/U9bNec9CQClALc8umLZ42b/h+OrV6XUsopNEAC9Qd2TUrl2Q933gUR+M/UKPW9tDtE+E52rLNmBkb/ShSvnbd32a6VZYid4zdVqIeLiMXhqHFBFLcgy5EXHyOb7K+vInQHHWlnhpFH+QYFYbNsuM9fM573AP3a7+UCJmB3sstFwHqF0pNScHYDzxRKGRw6/SsKfIY5Oa9wHHS/NfGv9uzZJSmQVtev5CjbkR9aJtt4Sj/34PrZ7XIjRCzziNHZK0pWvG8xDlL7nlsy7gN6Ta8/W7ag1+pDlrG76Ty8H8a9htm/YLxJpBeVYzQq0="
    - FAUNA_DOMAIN=rest.faunadb.com
    - FAUNA_SCHEME=https
    - FAUNA_PORT=443
script:
  - npm install
  - npm run test
